# -*- generated by 1.0.9 -*-
import da
_config_object = {}

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])
    _config_object = {'channel': 'Fifo', 'clock': 'Lamport'}

    def run(self):
        class_olympus = da.import_da('Olympus')
        class_client = da.import_da('Client')
        olympus = self.new(class_olympus.Olympus, args=(), at='OlympusNode')
        clientList = self.new(class_client.Client, num=3)
        i = 0
        for client in clientList:
            self._setup(client, args=(olympus, i))
            i += 1
        self._start(olympus)
        self._start(clientList)
