# -*- generated by 1.0.9 -*-
import da
_config_object = {}

class Shuttle():

    def __init__(self):
        self.action = None
        self.order_proof_list = None
        self.result_proof_list = None
        self.result = None
